services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - monitoring-network

  order-service:
    build:
      context: .
      dockerfile: src/Services/OrderService/Dockerfile
    image: orderservice:local
    container_name: order-service
    ports:
      - "5260:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__OrderDb: "Server=sqlserver,1433;Database=OrderDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
      OpenTelemetry__OtlpEndpoint: "http://otel-collector:4317"
      Services__CustomerService: "http://customer-service:8080"
      Services__PaymentService: "http://payment-service:8080"
    networks:
      - monitoring-network

  payment-service:
    build:
      context: .
      dockerfile: src/Services/PaymentService/Dockerfile
    image: paymentservice:local
    container_name: payment-service
    ports:
      - "5015:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__PaymentDb: "Server=sqlserver,1433;Database=PaymentDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
    networks:
      - monitoring-network

  customer-service:
    build:
      context: .
      dockerfile: src/Services/CustomerService/Dockerfile
    image: customerservice:local
    container_name: customer-service
    ports:
      - "5096:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__CustomerDb: "Server=sqlserver,1433;Database=CustomerDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
    networks:
      - monitoring-network

  product-service:
    build:
      context: .
      dockerfile: src/Services/ProductService/Dockerfile
    image: productservice:local
    container_name: product-service
    ports:
      - "5205:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__ProductDb: "Server=sqlserver,1433;Database=ProductDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
      OpenTelemetry__OtlpEndpoint: "http://otel-collector:4317"
    networks:
      - monitoring-network

volumes:
  sqlserver-data:

networks:
  monitoring-network:
    external: true