name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Build CustomerService Docker Image
        run: docker build -t customerservice:latest ./src/Services/CustomerService

      - name: Build OrderService Docker Image
        run: docker build -t orderservice:latest ./src/Services/OrderService

      - name: Build PaymentService Docker Image
        run: docker build -t paymentservice:latest ./src/Services/PaymentService
